
package java.web.learning.services.soap.servletclient;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonIF1", targetNamespace = "http://soap.services.learning.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonIF1 {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://soap.services.learning.web/", className = "Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://soap.services.learning.web/", className = "TestResponse")
    public void test();

}
