
package web.learning.services.soap.binary;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BinaryWSMTOM", targetNamespace = "http://soap.services.learning.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BinaryWSMTOM {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSomethingBinary", targetNamespace = "http://soap.services.learning.web/", className = "web.learning.services.soap.binary.GetSomethingBinary")
    @ResponseWrapper(localName = "getSomethingBinaryResponse", targetNamespace = "http://soap.services.learning.web/", className = "web.learning.services.soap.binary.GetSomethingBinaryResponse")
    public DataHandler getSomethingBinary(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0);

}
