
package com.millicom.rm.sync.client.clicklicense;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryClicLicenses", targetNamespace = "http://www.resourcesmanager.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryClicLicenses {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.millicom.rm.sync.client.clicklicense.QueryLicensesResponse
     * @throws QueryLicensesFault
     */
    @WebMethod(action = "http://www.resourcesmanager.com/queryClicLicenses")
    @WebResult(name = "queryLicensesResponse", targetNamespace = "http://xmlns.tigo.com/TigoFS/FieldServiceProxy/QueryClicLicensesResponse/V1/schema", partName = "parameters")
    public QueryLicensesResponse queryLicenses(
        @WebParam(name = "queryLicensesRequest", targetNamespace = "http://xmlns.tigo.com/TigoFS/FieldServiceProxy/QueryClicLicensesRequest/V1/schema", partName = "parameters")
        QueryLicensesRequest parameters)
        throws QueryLicensesFault
    ;

}
